language: java
env:
  matrix:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  global:
    secure: R57DPuAx1cb+DGlmczdCQYxUl/R+uu3tpKaKmEexEn5Mq6e8nw/g4HhsX1/tlR6Jl1vrnh8C/RIcaSU3hTvWQ9N4y59/36LHL+w/v3lOVd9J8jBFxhthl5Oypj0LrcENgMJjT7BoRqBt60gTZ2T0DcWgBgiAMLLmJAVgGeU6RWVS92TNCe7rUkXRBo+pLGaFimjllpe7+qRuuyGO36vTgTGsPumAq2YY1Ep1wJiCXE8PACXfTMDMhDCdiQMdzI5Jz9Qp8JrNA/JBBy3wCHimZyIREpqXINmHbdmCRsPMlpYoc5dDGFFL1AbtV7wZ8zu+8vYucil2OY24a5i6rrM680rRNlcUIZOYAAZS5HIYbXs9nECVNW9RVswlPtu07c+2ZXVst0jTnLvdJba4Rf5HhQBEE4QxXHuZ/KQKQE5asgTttvBsmkKyAb6cGImidCSNkgafaJRy/S7qy++DFh8c16YcJlf5oj/hCmiMu2qlX8X+6YJOiEy94ZqiJdZxR6+6W4bzN+xJfmCYcv2M6o7ZVxQoYzqwer7DDmKsL9xiwHdpVqniRgUbxrET23ugcX1K+LgVieUepSa112Xa67aEgCmCQGFJ0Cj8Xd0QmDmivbXIXdSfFLgBQTbNuYCQawIbCmc/3q5KgNtfGllXaqu+9l1iSwedBP18Tgz9VutfJPQ=
jdk:
- oraclejdk8
script:
- ./gradlew test -PideaVersion=$IDEA_VERSION
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
after_success:
- .travis/after_success.sh
before_install:
- openssl aes-256-cbc -K $encrypted_db8923e9d877_key -iv $encrypted_db8923e9d877_iv
  -in travis.enc -out .travis.ssh -d
- chmod 600 .travis.ssh
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile .travis.ssh\n" >> ~/.ssh/config
